; AGS2 run script
; ---------------
;RunFile=A-Magazines:C/CrackerJournal20/CrackerJournal20.Slave

; Favourites Mode
IF EXISTS ENV:ags2favouritesmode
  execute S:AGS2Favourites "C" "Cracker Journal 20 - Alpha"
  IF $ags2favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $ags2favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Run WHDLoad
cd "A-Magazines:C/CrackerJournal20/"
IF EXISTS ENV:whdloadargs
  whdload "CrackerJournal20.Slave" $whdloadargs
ELSE
  whdload "CrackerJournal20.Slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
